# build_ks_baseline.R
#
# Bootstrap + freeze the development KS baseline to R/ks_baseline.R (D20).
# Analogous to R/build_feature_breaks.R for CSI (D18).
#
# Generates a dev cohort via generate_cohort(), runs compute_ks_stats()
# on it, validates monotonicity and KS targets, then writes R/ks_baseline.R
# as literal R source (diffable, greppable, committed).

build_ks_baseline <- function(seed = 42L) {
  source(here::here("R/generate_cohort.R"))
  source(here::here("R/compute_ks.R"))

  result <- generate_cohort(seed = seed)
  dev <- result$dev_cohort

  # Compute KS through the same helper the Rmd uses
  ks_result <- compute_ks_stats(dev)

  # --- Validation ---
  dev_ks_targets <- c("0" = 42, "1" = 40, "2" = 38, "3" = 35, "4" = 28)
  dev_br_targets <- c("0" = 0.020, "1" = 0.045, "2" = 0.070,
                       "3" = 0.120, "4" = 0.065)

  for (seg in names(dev_ks_targets)) {
    seg_ks <- ks_result$ks_by_segment$ks_value[
      ks_result$ks_by_segment$segment == seg]
    if (abs(seg_ks - dev_ks_targets[seg]) > 1.5) {
      stop(sprintf("Seg %s: dev KS %.1f outside +-1.5 of target %d",
                   seg, seg_ks, dev_ks_targets[seg]))
    }
  }

  # Monotonicity: all segments should have monotonic decile bad rates
  for (seg in as.character(0:4)) {
    seg_rates <- ks_result$decile_rates[ks_result$decile_rates$segment == seg, ]
    seg_rates <- seg_rates[order(seg_rates$decile), ]
    diffs <- diff(seg_rates$bad_rate)
    if (any(diffs < 0)) {
      stop(sprintf("Seg %s: dev decile bad rates not monotonic", seg))
    }
  }

  # Average bads per decile per segment (total_bads / 10) must be >= 28
  # This is the statistical power check: at 3x volume, seg 0 yields ~28
  # bads/decile on average. Individual deciles can be much lower (decile 1
  # = highest scores = near-zero bads by design).
  for (seg in as.character(0:4)) {
    seg_bads <- ks_result$ks_by_segment$n_bads[
      ks_result$ks_by_segment$segment == seg]
    avg_per_decile <- seg_bads / 10
    if (avg_per_decile < 28) {
      stop(sprintf("Seg %s: avg bads/decile = %.0f, expected >= 28",
                   seg, avg_per_decile))
    }
  }

  message("Validation passed. Writing R/ks_baseline.R")

  # --- Write R/ks_baseline.R ---
  ks_tbl <- ks_result$ks_by_segment
  dr_tbl <- ks_result$decile_rates

  lines <- c(
    "# ks_baseline.R",
    "#",
    "# Frozen development baseline for KS comparison (D20).",
    "# Generated by R/build_ks_baseline.R. DO NOT edit manually.",
    "#",
    "# All segments have monotonic decile bad rates (validated at generation).",
    "# KS is computed on the decile grid via compute_ks_stats() — the same",
    "# helper the Rmd uses — so achieved == target by construction.",
    "",
    "ks_baseline <- list(",
    "  ks = tibble::tibble(",
    sprintf("    segment  = c(%s),",
            paste(sprintf('"%s"', ks_tbl$segment), collapse = ", ")),
    sprintf("    dev_ks   = c(%s),",
            paste(sprintf("%.1f", ks_tbl$ks_value), collapse = ", ")),
    sprintf("    dev_br   = c(%s),",
            paste(sprintf("%.4f",
              sapply(ks_tbl$segment, function(s) {
                d <- dr_tbl[dr_tbl$segment == s, ]
                sum(d$n_bads) / sum(d$n)
              })), collapse = ", ")),
    sprintf("    n_booked = c(%s)",
            paste(as.integer(ks_tbl$n_booked), collapse = ", ")),
    "  ),",
    "  decile_rates = tibble::tibble(",
    sprintf("    segment       = c(%s),",
            paste(sprintf('"%s"', dr_tbl$segment), collapse = ", ")),
    sprintf("    decile        = c(%s),",
            paste(as.integer(dr_tbl$decile), collapse = ", ")),
    sprintf("    dev_n         = c(%s),",
            paste(as.integer(dr_tbl$n), collapse = ", ")),
    sprintf("    dev_n_bads    = c(%s),",
            paste(as.integer(dr_tbl$n_bads), collapse = ", ")),
    sprintf("    dev_bad_rate  = c(%s),",
            paste(sprintf("%.6f", dr_tbl$bad_rate), collapse = ", ")),
    sprintf("    dev_min_score = c(%s),",
            paste(sprintf("%.0f", dr_tbl$min_score), collapse = ", ")),
    sprintf("    dev_max_score = c(%s)",
            paste(sprintf("%.0f", dr_tbl$max_score), collapse = ", ")),
    "  )",
    ")"
  )

  writeLines(lines, here::here("R/ks_baseline.R"))
  message("Wrote R/ks_baseline.R")

  invisible(ks_result)
}
